parameters:
#    application_tools.example.class: Application\ToolsBundle\Example

services:
#    application_tools.example:
#        class: %application_tools.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
